#!/usr/bin/perl -l

use strict;
use warnings;
use List::Util 'sum';

# The sequence of triangle numbers is generated by adding the natural numbers.
# So the 7th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28. The first
# ten terms would be:
#
#     1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...
#
# Let us list the factors of the first seven triangle numbers:
#
#   1: 1
#   3: 1,3
#   6: 1,2,3,6
#   10: 1,2,5,10
#   15: 1,3,5,15
#   21: 1,3,7,21
#   28: 1,2,4,7,14,28
#
# We can see that 28 is the first triangle number to have over five divisors.
# What is the value of the first triangle number to have over five hundred
# divisors?

my $i;
while (1) {
    $i++;

    # calculate the $i'th triangular number
    my $tri = $i * ($i + 1) / 2;
    my $ndiv = ndiv($tri);

    if ($i < 10) {
        print $i, ' => ', $tri, ' => ', $ndiv;
    }
    if ($i % 250 == 0) {
        print '... ', $i, ' => ', $tri, ' => ', $ndiv;
    }
    if ($ndiv > 500) {
        print $i, ' => ', $tri, ' => ', $ndiv;
        last;
    }
}

# return the number of divisors
sub ndiv {
    my $n = shift;
    my $count;
    for (my $i = 1; $i * $i < $n; $i++) {
        next unless $n % $i == 0;
        $count += 2;
    }
    return $count;
}

