#!/usr/bin/perl -l

use strict;
use warnings;
use Data::Dumper;

unless (caller()) {
    for my $i (1 .. 1_000_000) {
        my $t = $i * ($i + 1) / 2;
        next unless is_pentagonal($t);
        next unless is_hexagonal($t);
        print "$i => $t";
    }
}

sub is_pentagonal {
    my $n = shift;
    my $i = (1 + sqrt(24 * $n + 1)) / 6;
    return (abs($i - int($i)) < 1e-9) ? 1 : 0;
}

sub is_hexagonal {
    my $n = shift;
    my $i = (1 + sqrt(8 * $n + 1)) / 4;
    return (abs($i - int($i)) < 1e-9) ? 1 : 0;
}



1;

__END__

Triangle, pentagonal, and hexagonal numbers are generated by the following
formulae:

    Triangle     T(n) = n(n+1)/2      1, 3, 6, 10, 15, ...
    Pentagonal   P(n) = n(3n-1)/2     1, 5, 12, 22, 35, ...
    Hexagonal    H(n) = n(2n-1)       1, 6, 15, 28, 45, ...

It can be verified that T(285) = P(165) = H(143) = 40755.

Find the next triangle number that is also pentagonal and hexagonal.


